### PR TITLE
Adding platform.io support

### PR DESCRIPTION
**Pull request by tbaumann**
Initial platformio.ini

Fixes https://github.com/G4lile0/ESP32-WiFi-Hash-Monster/issues/11

### CODE REVIEW

**Comment by tobozo** [comment]
Thanks for this contribution :+1: 

```ini
[env:m5stack-core-esp32]

board = m5stack-core-esp32
```

Since M5Fire is the default device for this project, I'd recommend using a default `m5stack-fire` board instead of `m5stack-core-esp32` , and leave a list of all other possible boards in a comment

env/board can be one of :  `m5stack-fire`, `odroid_esp32`, `m5stack-core-esp32` or `m5stack-core2` (though M5Core2 may require a bit more customizations)

**Comment by tbaumann** [comment]
Sure, I can do that. Thanks

**Comment by G4lile0** [comment]
Great! Thanks a lot !

**Comment by dannykansas** [comment]
This is very appreciated; I grabbed a M5Stack Core2 on accident (with zero previous experience with IoT dev), and this got me up and running quickly after failing through Arduino IDE methods. 👏

**Pull request merged**
